import { Buffer } from "node:buffer";

import { AgentRuntime } from "../../../packages/sdk/src/index.js";

const hubUrl = process.env.HUB_URL ?? "ws://127.0.0.1:8787/ws";
const agentId = process.env.AGENT_ID ?? "demo-agent";

const runtime = new AgentRuntime({
  hubUrl,
  agentId,
  displayName: "Demo Agent",
  kind: "demo-agent",
  capabilities: ["status", "stop", "retry", "approve", "send_text", "custom"],
  quickCommands: ["status", "approve", "retry", "stop"]
});

async function publishDemoImage(): Promise<void> {
  const svg = [
    "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"640\" height=\"360\">",
    "<rect width=\"640\" height=\"360\" fill=\"#101820\" />",
    "<rect x=\"24\" y=\"24\" width=\"592\" height=\"312\" rx=\"20\" fill=\"#1f3a5f\" />",
    "<text x=\"48\" y=\"110\" fill=\"#f2f7ff\" font-size=\"42\" font-family=\"monospace\">Personal Private Agent IM</text>",
    "<text x=\"48\" y=\"170\" fill=\"#9fd3ff\" font-size=\"24\" font-family=\"monospace\">Demo artifact from agent</text>",
    "<text x=\"48\" y=\"220\" fill=\"#d4e9ff\" font-size=\"20\" font-family=\"monospace\">status: need approval</text>",
    "</svg>"
  ].join("");

  await runtime.uploadArtifact({
    kind: "image",
    fileName: "demo-preview.svg",
    mimeType: "image/svg+xml",
    caption: "Demo preview generated by the agent",
    contentBase64: Buffer.from(svg, "utf8").toString("base64")
  });
}

async function bootstrap(): Promise<void> {
  await runtime.connect();
  await runtime.emitEvent({
    eventType: "task_running",
    title: "Task running",
    body: "Demo agent connected and waiting for commands",
    status: "busy"
  });
  await runtime.emitEvent({
    eventType: "need_approval",
    title: "Need approval",
    body: "Approve the demo task or send more instructions",
    status: "waiting_input"
  });
  await publishDemoImage();
}

runtime.onCommand(async (command) => {
  switch (command.type) {
    case "status":
      await runtime.sendText("Current status", "Demo agent is online and waiting for instructions.");
      break;
    case "approve":
      await runtime.emitEvent({
        eventType: "task_running",
        title: "Approval accepted",
        body: "The demo task resumed after approval",
        status: "busy"
      });
      await runtime.emitEvent({
        eventType: "task_completed",
        title: "Task completed",
        body: "Demo task finished successfully",
        status: "completed"
      });
      break;
    case "retry":
      await runtime.emitEvent({
        eventType: "task_running",
        title: "Retry scheduled",
        body: "The demo task restarted",
        status: "busy"
      });
      break;
    case "send_text":
      await runtime.sendText("Instruction received", command.text ?? "");
      break;
    case "stop":
      await runtime.close();
      process.exit(0);
      break;
    case "custom":
      if (command.text === "image_demo") {
        await publishDemoImage();
      }
      break;
  }
});

bootstrap().catch((error) => {
  console.error("demo agent failed", error);
  process.exit(1);
});
